### ISSUE TITLE
README: How to navigate to "Hashes tagged: foo" panel?

### ISSUE THREAD

**Issue by ybakos** [scmilee/filesystem-prototype#11]
I can create and search... but how do I select the hash in the right "hashes tagged" panel such that the contents of the message appear?

**Comment by scmilee** [comment]
after highlighting a hash in the right panel, hit enter to see the contents.

**Comment by ybakos** [comment]
@scmilee Highlight by clicking? I can't seem to highlight it. (sorry)

**Comment by scmilee** [comment]
By default the focus of the TUI shifts to the  "hashes tagged" panel after searching for a tag. So you should be able to use the arrow keys to switch between the hashes then hit enter to resolve them.

**Comment by ybakos** [comment]
Got it.
