### ISSUE TITLE
dev/invoke.js and dev/tui.js: Why a dev subdirectory?

### ISSUE THREAD

**Issue by ybakos** [scmilee/filesystem-prototype#13]
Seems the project has three main subdirs:

- cli: Old cli subpackage (is this relevant / useful any more?) 
- lib: main classes used by the tui (?)
- dev: scripts to run the tui and ?

Are the purposes I note above accurate or no? Are there things that can now be deleted?

I recommend keeping:

- a cli that can create / search / display rhizome info nuggets from the command-line
- a tui that can create / search / display rhizome info nuggets within a tui

Let me know if I'm off here. I can't tell what should be organized where, and my intent is to help with this.

**Comment by scmilee** [comment]
If we want to keep cli functionality we should keep the cli subdirectory and build on it as needed to support a cli.
 
Lib is where all library functionality resides for the public file manager and private file manager(logic for sharing personal files across devices). Currently I believe the tui file can be separated from the lib folder and into its own directory. 

The dev directory is to initialize and run these libraries together locally in a dev environment. Originally the dev/invoke function was running the tui and a private file manager but It can now just be deleted.

lib/public_directory can be destroyed as it serves the same purpose as the tui. 
the original index should be kept as is if we want to keep this as a library, but we could move the dev/tui script in there if we want this to be a TUI.

**Comment by ybakos** [comment]
Ok. What about:

- lib/tui: tui-specific modules/classes, etc.
- lib/cli: cli-specific module/classes, etc.
- lib/shared: things than both the tui and cli use (eg file managers)
-bin/cli.js, bin/tui.js, etc for the main scripts for launching cli, tui, etc.

The current cli/ subdir looks like its own package... let's integrate into the main package.

Let me know if none of this makes sense or is a Bad Idea.

**Comment by scmilee** [comment]
Sounds good, bin is more descriptive of the functionality.

**Comment by ybakos** [comment]
So....
```
- /
- index.js: contains exports of lib/shared/* stuff for others to use this as a lib (?)
-- bin/
--- tui.js
--- cli.js
--- any other thing that needs to be run from the command line
-- lib/
--- cli/
---- cli-specific stuff here. No package.json, this is not a package
--- tui/
---- tui-specific stuff here.
--- shared/
---- classes /modules that are common to tui, cli, etc.
```

**Comment by scmilee** [comment]
looks good 👍
